language: android
android:
  components:
    - build-tools-21.1.2
    - android-21
    - extra
    - sys-img-armeabi-v7a-android-21
    - sys-img-x86-android-21
script:
  - ./gradlew clean prepareDebugDependencies
  - ./gradlew test
  - ./gradlew connectedAndroidTest
