language: android

jdk:
  - oraclejdk7
  - oraclejdk8

android:
  components:
    - build-tools-22.0.1
    - extra-android-m2repository
    - extra-google-m2repository
    - android-22

script:
  - ./gradlew connectedCheck
  - ./gradlew connectedAndroidTest
  - ./gradlew test
